Document: aravis
Title: Debian aravis Manual
Author: <insert document author here>
Abstract: This manual describes what aravis is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/aravis/aravis.sgml.gz

Format: postscript
Files: /usr/share/doc/aravis/aravis.ps.gz

Format: text
Files: /usr/share/doc/aravis/aravis.text.gz

Format: HTML
Index: /usr/share/doc/aravis/html/index.html
Files: /usr/share/doc/aravis/html/*.html
